### ISSUE TITLE
i18n: Korean translation

### ISSUE THREAD

**Issue by 1dentity84** [plctlab/plctlab.github.io#27]
We need to translate the homepage into Korean and here is what we need to translate:
@alapha23
- [x] https://github.com/plctlab/plctlab.github.io/blob/92476a4142b8a82378d0a90b747a39d2d758d4e3/content/ko/_index.md?plain=1#L2
- [x] https://github.com/plctlab/plctlab.github.io/blob/92476a4142b8a82378d0a90b747a39d2d758d4e3/content/ko/_index.md?plain=1#L3
- [x] https://github.com/plctlab/plctlab.github.io/blob/92476a4142b8a82378d0a90b747a39d2d758d4e3/content/ko/_index.md?plain=1#L10
- [x] project summary in every `projects/project{1-5}` https://github.com/plctlab/plctlab.github.io/blob/92476a4142b8a82378d0a90b747a39d2d758d4e3/content/ko/projects/project1/index.md?plain=1#L4

**Comment by alapha23** [comment]
[PR](https://github.com/plctlab/plctlab.github.io/pull/32) is up

**Comment by alapha23** [comment]
#35
