### ISSUE TITLE
i18n: Russian translation

### ISSUE THREAD

**Issue by 1dentity84** [plctlab/plctlab.github.io#29]
We need to translate the homepage into Russian and here is what we need to translate:
@ArchFeh 
- [x] https://github.com/plctlab/plctlab.github.io/blob/92476a4142b8a82378d0a90b747a39d2d758d4e3/content/ru/_index.md?plain=1#L2
- [x] https://github.com/plctlab/plctlab.github.io/blob/92476a4142b8a82378d0a90b747a39d2d758d4e3/content/ru/_index.md?plain=1#L3
- [x] https://github.com/plctlab/plctlab.github.io/blob/92476a4142b8a82378d0a90b747a39d2d758d4e3/content/ru/_index.md?plain=1#L10
- [x] project summary in every `projects/project{1-5}` https://github.com/plctlab/plctlab.github.io/blob/92476a4142b8a82378d0a90b747a39d2d758d4e3/content/ru/projects/project1/index.md?plain=1#L4

**Comment by AMiracle-creator** [comment]
Hello,  I can do this, I'll be happy to help!

**Comment by ArchFeh** [comment]
> Hello, I can do this, I'll be happy to help!

Hello! Thank you for your help, PR welcome :)

**Comment by AMiracle-creator** [comment]
Hello, issue done. Check pull request
