### ISSUE TITLE
PLCT Open Wishlist for RISC-V 2021

### ISSUE THREAD

**Issue by lazyparser** [plctlab/plctlab.github.io#7]
The PLCT Lab is inviting everyone inside the RISC-V community to write to us
the dev-tools or other softwares you wish to have in the RISC-V ecosystem.
Feel free to open an issue on plctlab.org[0] and describe the tools you want.

A few simple rules should be met:
- Only open source projects are considered.
- Softwares that have not been ported to RV64G are prefered.
- Language VMs, Compilers, and Performance Analyzing tools are prefered.

There are some items already on the wishlist:
1. Enable Firefox/Spidermonkey running on RV64GCV platform[8].
2. Speed up more than 100x compared with OpenJDK/zero for Java applications[7].
3. Ensure the speed of JS/WASM on RV64GCV is on par with AArch64.
4. Enable DynamoRIO running on RV64GC.

Feel free to contact us and add more items on the wishlist.

**Comment by wuyanjun** [comment]
A global map for RISC-V software ecosystem is needed, so that everyone can lookup and query status of a specific software easily.  Though we do have a link in GitHub https://github.com/riscv/riscv-software-list, it is not well-organized and user-friendly.

**Comment by lazyparser** [comment]
https://plctlab.github.io/PLCT-Roadmap-2021.html
