### ISSUE TITLE
LuaJIT RV64GC port

### ISSUE THREAD

**Issue by davidlt** [plctlab/plctlab.github.io#9]
While Lua works on riscv64 (RV64GC) many projects choose to use LuaJIT (I believe it's Lua 5.1 compatible). This also means that projects don't support new Lua versions (e.g. 5.3 or 5.4) as they intention is to use LuaJIT. One of such example could be EFL package (but there would be more): https://git.enlightenment.org/core/efl.git/

References:
https://archive.fosdem.org/2020/schedule/event/riscv_luajit/
https://www.reddit.com/r/RISCV/comments/95k15i/luajit_on_riscv/
https://github.com/LuaJIT/LuaJIT/issues/628

**Comment by lazyparser** [comment]
Hi @davidlt

Thank you very much. We'll add the LuaJIT to the PLCT RISC-V Roadmap 2021.

**Comment by apivovarov** [comment]
`libluajit` is needed for `sysbench`!

**Comment by lazyparser** [comment]
merged into

https://plctlab.github.io/PLCT-Roadmap-2021.html
